import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { PLYLoader } from 'three/addons/loaders/PLYLoader.js';

// Setup Three.js Scene
const container = document.getElementById('threeViewer');
const loading = document.getElementById('loading3d');

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x050505);

// Camera
const camera = new THREE.PerspectiveCamera(50, container.clientWidth / container.clientHeight, 0.1, 1000);
camera.position.set(0, -2, 5);

// Renderer
const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setSize(container.clientWidth, container.clientHeight);
renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));
if (THREE.sRGBEncoding) renderer.outputEncoding = THREE.sRGBEncoding;
container.appendChild(renderer.domElement);

// Controls
const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.05;

// Load PLY Point Cloud
const loader = new PLYLoader();
loader.load(
    'assets/point_cloud.ply',
    function (geometry) {
        geometry.computeVertexNormals();

        // Create point material (using vertex colors generated by OpenCV)
        const material = new THREE.PointsMaterial({
            size: 0.05,
            vertexColors: true,
            sizeAttenuation: true
        });

        const points = new THREE.Points(geometry, material);

        // Center the geometry
        geometry.computeBoundingBox();
        const center = new THREE.Vector3();
        geometry.boundingBox.getCenter(center);
        points.position.sub(center);

        // Rotate if necessary to match Z-up coordinate system
        points.rotation.x = -Math.PI / 2;

        scene.add(points);
        loading.style.display = 'none';

        // Auto-fit camera
        const maxDim = Math.max(
            geometry.boundingBox.max.x - geometry.boundingBox.min.x,
            geometry.boundingBox.max.y - geometry.boundingBox.min.y,
            geometry.boundingBox.max.z - geometry.boundingBox.min.z
        );

        camera.position.z = maxDim * 1.5;

        // Scale point size for visibility on large/small models
        material.size = Math.max(0.01, maxDim * 0.02);

        controls.update();
    },
    function (xhr) {
        if (xhr.lengthComputable) {
            const percent = Math.round((xhr.loaded / xhr.total) * 100);
            loading.innerText = `Loading 3D Point Cloud... ${percent}%`;
        }
    },
    function (error) {
        console.error('An error happened loading the PLY file:', error);
        loading.innerText = 'Failed to load 3D Model.';
        loading.style.color = '#ff4444';
    }
);

// Animation Loop
function animate() {
    requestAnimationFrame(animate);
    controls.update();
    renderer.render(scene, camera);
}
animate();

// Handle Window Resize
window.addEventListener('resize', () => {
    if (container.clientWidth > 0) {
        camera.aspect = container.clientWidth / container.clientHeight;
        camera.updateProjectionMatrix();
        renderer.setSize(container.clientWidth, container.clientHeight);
        renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));
    }
});
